server:
  port: 80


# druid ?????
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ssm_db_2?serverTimezone=UTC&characterEncoding-utf8
      username: root
      password: zsy983715708


# mybatis-plus
mybatis-plus:
  global-config:
    db-config:
      table-prefix: tbl_
      id-type: auto # ????


  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl